[package]
name = "ggga"
version = "0.1.0"
authors = ["Vladimir Shakhov <bogdad@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.20.0"
vulkano-shaders = "0.20.0"
winit = "0.24"
vulkano-win = "0.20.0"
cgmath = "0.17.0"
gltf = "0.15.2"

